<a href="https://colab.research.google.com/github/Alan-Roza/IA/blob/main/01_Introducao_Scikit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aula 01 - Introdução ao Scikit-Learn
#### Material baseado no livro "Practical Machine Learning with Python" Sarkar, D. (et al.) (2018)

---

# Numpy
## Arrays

In [1]:
import numpy as np
arr = np.array([1,3,4,5,6])
arr

array([1, 3, 4, 5, 6])

In [2]:
arr.shape

(5,)

In [3]:
arr.dtype

dtype('int64')

In [4]:
arr = np.array([1,'st','er',3])
arr.dtype

dtype('<U21')

In [ ]:
#np.sum(arr)

### Creating arrays

In [5]:
arr = np.array([[1,2,3],[2,4,6],[8,8,8]])
arr.shape

(3, 3)

In [6]:
arr

array([[1, 2, 3],
       [2, 4, 6],
       [8, 8, 8]])

In [7]:
arr = np.zeros((2,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
arr = np.ones((2,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
arr = np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Random based on normal curve (n from randn)

In [10]:
arr = np.random.randn(3,4)
arr

array([[ 1.95445154, -0.05615093,  1.1001374 ,  1.12270231],
       [ 1.49317109, -1.32970062, -0.8297254 , -0.14800251],
       [ 0.55412326,  0.98597983,  0.35465754, -0.09121396]])

### Accessing array elements
#### Simple indexing

In [11]:
arr[1]

array([ 1.49317109, -1.32970062, -0.8297254 , -0.14800251])

arange(12) sequence between 0 to 12 creating an array;
reshape is used to change dimensions of shape of the array

In [12]:
arr = np.arange(12).reshape(2,2,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [ ]:
arr[0]

Its a slice. arr[from:to]

In [ ]:
arr = np.arange(10)
arr[5:]


Get all data between 5 and 8 index from arr

In [ ]:
arr[5:8]

Get the last 5 index from arr

In [ ]:
arr[:-5]

In [ ]:
arr = np.arange(12).reshape(2,2,3)
arr

In [ ]:
arr[1:2]

In [ ]:
arr = np.arange(27).reshape(3,3,3)
arr

get third dimension from arr

In [ ]:
arr[:,:,2]

In [ ]:
arr[...,2]

#### Advanced Indexing

In [13]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
arr[[0,1,2],[1,0,0]]

array([1, 3, 6])

##### Boolean Indexing

In [15]:
cities = np.array(["delhi","banglaore","mumbai","chennai","bhopal"])
city_data = np.random.randn(5,3)
city_data

array([[-0.64178375,  0.6684717 ,  0.27264215],
       [ 0.19787513, -0.10477848, -0.21984104],
       [ 0.4181542 , -1.36056957, -0.20541018],
       [-0.37674228, -0.11698533, -0.14982545],
       [ 0.39878468,  0.01556141,  0.54892498]])

boolean array is called mask and is inserted inside the index of arrays

In [16]:
city_data[cities =="delhi"]

array([[-0.64178375,  0.6684717 ,  0.27264215]])

set all values up to some value is set to 0, for example. Its used to remove outliers

In [17]:
city_data[city_data >0]

array([0.6684717 , 0.27264215, 0.19787513, 0.4181542 , 0.39878468,
       0.01556141, 0.54892498])

In [18]:
city_data[city_data >0] = 0
city_data


array([[-0.64178375,  0.        ,  0.        ],
       [ 0.        , -0.10477848, -0.21984104],
       [ 0.        , -1.36056957, -0.20541018],
       [-0.37674228, -0.11698533, -0.14982545],
       [ 0.        ,  0.        ,  0.        ]])

#### Operations on arrays

In [20]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
arr + 5

multiple all index from arr for 2

In [21]:
arr * 2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

arr2 + arr1 its a sum of matriz

In [ ]:
arr1 = np.arange(15).reshape(5,3)
arr2 = np.arange(5).reshape(5,1)
arr2 + arr1


In [ ]:
arr1

In [ ]:
arr2

In [23]:
arr1 = np.random.randn(5,3)
arr1

array([[ 0.1337151 ,  0.58737883, -0.64331892],
       [ 0.91089186, -1.12937473,  0.56626124],
       [-0.24055192,  1.3075502 ,  0.98015897],
       [-0.331491  ,  0.78609557,  1.24241028],
       [ 0.95115772, -1.61589166, -0.76368331]])

modf remove all decimal numbers inside an array

In [22]:
np.modf(arr1)

NameError: ignored

#### Linear algebra using numpy

A multiple B (dot is used to multiple matrix)

In [24]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[1,2,3]])
A.dot(B)

array([[ 24,  24,  24],
       [ 72,  69,  66],
       [120, 114, 108]])

.T = Transpost

In [ ]:
A = np.arange(15).reshape(3,5)
A.T

# Pandas
## Data frames

DataFrame is used to create a dataset, use an array of dictionaries

In [28]:
import pandas as pd
d =  [{'city':'Delhi',"data":1000},
      {'city':'Banglaore',"data":2000},
      {'city':'Mumbai',"data":1000}]
pd.DataFrame(d)

city  data
0      Delhi  1000
1  Banglaore  2000
2     Mumbai  1000

In [26]:
df = pd.DataFrame(d)

### Reading in data

In [30]:
city_data = pd.read_csv(filepath_or_buffer='simplemaps-worldcities-basic.csv')

Get first 10 rows of dataset

In [ ]:
city_data.head(n=10)

Get the last 5 rows from dataset

In [31]:
city_data.tail()

city   city_ascii        lat        lng        pop   country  \
7317       Mutare       Mutare -18.970019  32.650038   216785.0  Zimbabwe   
7318       Kadoma       Kadoma -18.330006  29.909947    56400.0  Zimbabwe   
7319  Chitungwiza  Chitungwiza -18.000001  31.100003   331071.0  Zimbabwe   
7320       Harare       Harare -17.817790  31.044709  1557406.5  Zimbabwe   
7321     Bulawayo     Bulawayo -20.169998  28.580002   697096.0  Zimbabwe   

     iso2 iso3          province  
7317   ZW  ZWE        Manicaland  
7318   ZW  ZWE  Mashonaland West  
7319   ZW  ZWE            Harare  
7320   ZW  ZWE            Harare  
7321   ZW  ZWE          Bulawayo

Its used to get the column from dataset

In [33]:
series_es = city_data.lat

In [34]:
type(series_es)

pandas.core.series.Series

In [35]:
series_es[1:10:2]

1    34.516701
3    31.112001
5    32.850000
7    36.729999
9    34.650000
Name: lat, dtype: float64

In [ ]:
series_es[:7]

In [ ]:
series_es[:-7315]

Slice inside the dataset

In [ ]:
city_data[:7]

iloc is to use index in pandas to manipulate the dataset

In [ ]:
city_data.iloc[:5,:4]

[city_data['pop'] > 10000000] = create a mask population is greater than 10000000 |
pd.Series(city_data.columns).str = transform an array in a serie and convert to string | .startswith('l') = get columns that starts with 'l' (column name).

In [ ]:
city_data[city_data['pop'] > 10000000][city_data.columns[pd.Series(city_data.columns).str.startswith('l')]]

In [ ]:
city_greater_10mil = city_data[city_data['pop'] > 10000000]
city_greater_10mil.rename(columns={'pop':'population'}, inplace=True) # rename the column name, inplace: do at the same variable that its running (by reference)
city_greater_10mil.where(city_greater_10mil.population > 15000000) # Its igual the first line, but using where and doing by reference

In [37]:
df = pd.DataFrame(np.random.randn(8, 3),
columns=['A', 'B', 'C'])

### Operations on dataframes

.values show all values from the dataset

In [ ]:
nparray = df.values
type(nparray)

In [38]:
from numpy import nan
df.iloc[4,2] = nan

In [39]:
df

A         B         C
0  1.285611 -0.034282  0.829172
1  0.037797 -1.090855 -1.200803
2 -0.150240 -0.538509  0.957530
3 -0.905366 -0.571897 -0.604816
4 -2.161881  0.092003       NaN
5  0.737817 -0.715550  0.170174
6  0.550151 -0.476324  1.295440
7  0.954796  1.348661  1.686296

fill every place that is NaN in dataset for some value, in this case 0

In [ ]:
df.fillna(0)

In [ ]:
columns_numeric = ['lat','lng','pop']

In [40]:
city_data[columns_numeric].mean()

NameError: ignored

In [ ]:
city_data[columns_numeric].sum()

In [ ]:
city_data[columns_numeric].count()

In [ ]:
city_data[columns_numeric].median()

In [ ]:
city_data[columns_numeric].quantile(0.8)

In [ ]:
city_data[columns_numeric].sum(axis = 1).head()

In [ ]:
city_data[columns_numeric].describe()

In [ ]:
city_data1 = city_data.sample(3)

### Concatanating data frames

concat two dataset, its pretty similar to join in sql

In [ ]:
city_data2 = city_data.sample(3)
city_data_combine = pd.concat([city_data1,city_data2])
city_data_combine

remove duplicated rows, for training its better remove all diplicated values

In [ ]:
country_data = city_data[['iso3','country']].drop_duplicates()

In [ ]:
country_data.shape

In [ ]:
country_data.head()

In [ ]:
del(city_data['country'])

In [ ]:
city_data.merge(country_data, 'inner').head()

# Scikit-learn

In [41]:
from sklearn import datasets
diabetes = datasets.load_diabetes()
X = diabetes.data[:10]
y = diabetes.target

In [42]:
X[:5]

array([[ 0.03807591,  0.05068012,  0.06169621,  0.02187239, -0.0442235 ,
        -0.03482076, -0.04340085, -0.00259226,  0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, -0.02632753, -0.00844872,
        -0.01916334,  0.07441156, -0.03949338, -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, -0.00567042, -0.04559945,
        -0.03419447, -0.03235593, -0.00259226,  0.00286131, -0.02593034],
       [-0.08906294, -0.04464164, -0.01159501, -0.03665608,  0.01219057,
         0.02499059, -0.03603757,  0.03430886,  0.02268774, -0.00936191],
       [ 0.00538306, -0.04464164, -0.03638469,  0.02187239,  0.00393485,
         0.01559614,  0.00814208, -0.00259226, -0.03198764, -0.04664087]])

In [43]:
y[:10]

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310.])

In [44]:
feature_names=['age', 'sex', 'bmi', 'bp',
               's1', 's2', 's3', 's4', 's5', 's6']

## Scikit example regression

X = attributes | y = target | Lasso() tries to plot a line pretty close all points

In [45]:
from sklearn import datasets
from sklearn.linear_model import Lasso

from sklearn import linear_model, datasets
from sklearn.model_selection import GridSearchCV

diabetes = datasets.load_diabetes()
X_train = diabetes.data[:310]
y_train = diabetes.target[:310]

X_test = diabetes.data[310:]
y_test = diabetes.target[310:]

learner = Lasso(random_state=0)
alphas = np.logspace(-4, -0.5, 30)

learner.fit(X_train, y_train)

Lasso(random_state=0)

In [46]:
y_pred = learner.predict(X_test)
y_pred

array([167.65740976, 169.41733534, 129.69001805, 188.50968503,
       161.07613773, 140.22683569, 181.63125908, 147.46537223,
       156.6244556 , 162.42686029, 173.00350182, 202.95389815,
       218.21473297, 192.50670204, 175.56271442, 198.88069029,
       158.32191972, 191.0334113 , 174.08378546, 125.64157893,
       153.66199999, 128.00649334, 207.32108823, 158.86094006,
       113.02173567, 116.57138682, 208.64338664, 148.43306144,
       131.72426149, 163.30940035, 133.99719963, 163.48591879,
       150.6351001 , 137.8465945 , 149.37123585, 149.79190025,
       178.53976654, 141.80700947, 140.22683569, 109.83213345,
       196.27739144, 117.03665774, 118.86206812, 176.62489451,
       192.33941556, 136.38768825, 129.7431493 , 185.5209981 ,
        93.13905725, 158.08414225, 162.86805614, 123.87687072,
       189.1023203 , 148.98282441, 153.9221549 , 148.15695923,
       223.41792389, 222.39899953, 181.07383847, 162.62397183,
       109.83213345, 188.44708674, 139.09174823, 132.82

MAE - Erro da reta

In [47]:
np.mean(abs(y_pred - y_test))

51.37622164032987